-- ============================================
-- 02: BRONZE LAYER (Raw Data + Hybrid VARIANT)
-- ============================================

CREATE OR REPLACE TABLE KAGGLE_DB.BRONZE.RAW_TRANSACTIONS AS
SELECT
    ID,
    TRANS_DATE_TRANS_TIME,
    CC_NUM,
    MERCHANT,
    CATEGORY,
    AMT,
    FIRST,
    LAST,
    GENDER,
    STREET,
    CITY,
    STATE,
    ZIP,
    LAT,
    LONG,
    CITY_POP,
    JOB,
    DOB,
    TRANS_NUM,
    UNIX_TIME,
    MERCH_LAT,
    MERCH_LONG,
    IS_FRAUD,
    CURRENT_TIMESTAMP() AS INGESTED_AT
FROM KAGGLE_DB.FRAUD_ANALYSIS.FRAUD_TEST;

ALTER TABLE KAGGLE_DB.BRONZE.RAW_TRANSACTIONS ADD COLUMN RAW_DATA VARIANT;

UPDATE KAGGLE_DB.BRONZE.RAW_TRANSACTIONS
SET RAW_DATA = OBJECT_CONSTRUCT(
    'ID', ID, 'TRANS_DATE_TRANS_TIME', TRANS_DATE_TRANS_TIME,
    'CC_NUM', CC_NUM, 'MERCHANT', MERCHANT, 'CATEGORY', CATEGORY,
    'AMT', AMT, 'FIRST', FIRST, 'LAST', LAST, 'GENDER', GENDER,
    'STREET', STREET, 'CITY', CITY, 'STATE', STATE, 'ZIP', ZIP,
    'LAT', LAT, 'LONG', LONG, 'CITY_POP', CITY_POP,
    'JOB', JOB, 'DOB', DOB, 'TRANS_NUM', TRANS_NUM,
    'UNIX_TIME', UNIX_TIME, 'MERCH_LAT', MERCH_LAT,
    'MERCH_LONG', MERCH_LONG, 'IS_FRAUD', IS_FRAUD
);

ALTER TABLE KAGGLE_DB.BRONZE.RAW_TRANSACTIONS SET CHANGE_TRACKING = TRUE;

-- Pipeline monitoring tables
CREATE OR REPLACE TABLE KAGGLE_DB.BRONZE.PIPELINE_ERROR_LOG (
    ERROR_ID NUMBER AUTOINCREMENT,
    PROCEDURE_NAME VARCHAR(100),
    ERROR_CODE VARCHAR(20),
    ERROR_MESSAGE VARCHAR(5000),
    ERROR_STATE VARCHAR(20),
    STACK_TRACE VARCHAR(10000),
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE KAGGLE_DB.BRONZE.PIPELINE_EXECUTION_LOG (
    EXECUTION_ID NUMBER AUTOINCREMENT,
    PROCEDURE_NAME VARCHAR(100),
    EXECUTION_STATUS VARCHAR(20),
    START_TIME TIMESTAMP_LTZ,
    END_TIME TIMESTAMP_LTZ,
    DURATION_SECONDS NUMBER,
    ROWS_INSERTED NUMBER DEFAULT 0,
    ROWS_UPDATED NUMBER DEFAULT 0,
    ROWS_PROCESSED NUMBER DEFAULT 0,
    SOURCE_LAG_SECONDS NUMBER,
    BATCH_TIMESTAMP TIMESTAMP_LTZ,
    WAREHOUSE_NAME VARCHAR(50),
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE KAGGLE_DB.BRONZE.SCHEMA_REGISTRY (
    REGISTRY_ID NUMBER AUTOINCREMENT,
    LAYER VARCHAR(10),
    TABLE_NAME VARCHAR(100),
    COLUMN_NAME VARCHAR(100),
    DATA_TYPE VARCHAR(50),
    CHANGE_TYPE VARCHAR(20),
    DETECTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_PROPAGATED BOOLEAN DEFAULT FALSE,
    PROPAGATED_AT TIMESTAMP_LTZ
);
