-- ============================================
-- 03: SILVER LAYER (Enriched + Scored)
-- ============================================

CREATE OR REPLACE TABLE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS AS
SELECT
    ID,
    TRANS_DATE_TRANS_TIME,
    CC_NUM,
    MERCHANT,
    CATEGORY,
    AMT,
    FIRST,
    LAST,
    GENDER,
    STREET,
    CITY,
    STATE,
    ZIP,
    LAT,
    LONG,
    CITY_POP,
    JOB,
    DOB,
    TRANS_NUM,
    UNIX_TIME,
    MERCH_LAT,
    MERCH_LONG,
    IS_FRAUD,
    INGESTED_AT,
    DATEDIFF('YEAR', DOB, TRANS_DATE_TRANS_TIME) AS AGE,
    HOUR(TRANS_DATE_TRANS_TIME) AS TRANSACTION_HOUR,
    DAYNAME(TRANS_DATE_TRANS_TIME) AS TRANSACTION_DAY,
    DATE_TRUNC('MONTH', TRANS_DATE_TRANS_TIME) AS TRANSACTION_MONTH,
    CASE
        WHEN AMT < 10 THEN 'MICRO'
        WHEN AMT < 50 THEN 'SMALL'
        WHEN AMT < 200 THEN 'MEDIUM'
        WHEN AMT < 500 THEN 'LARGE'
        ELSE 'VERY_LARGE'
    END AS AMOUNT_BUCKET,
    HAVERSINE(LAT, LONG, MERCH_LAT, MERCH_LONG) AS DISTANCE_KM,
    CASE
        WHEN HOUR(TRANS_DATE_TRANS_TIME) BETWEEN 0 AND 5 THEN 'LATE_NIGHT'
        WHEN HOUR(TRANS_DATE_TRANS_TIME) BETWEEN 6 AND 11 THEN 'MORNING'
        WHEN HOUR(TRANS_DATE_TRANS_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
        ELSE 'EVENING'
    END AS TIME_OF_DAY,
    -- Timezone mapping
    CASE
        WHEN STATE IN ('CT','DC','DE','FL','GA','IN','KY','MA','MD','ME','MI','NC','NH','NJ','NY','OH','PA','RI','SC','VA','VT','WV') THEN 'America/New_York'
        WHEN STATE IN ('AL','AR','IA','IL','KS','LA','MN','MO','MS','ND','NE','OK','SD','TN','TX','WI') THEN 'America/Chicago'
        WHEN STATE IN ('AZ','CO','ID','MT','NM','UT','WY') THEN 'America/Denver'
        WHEN STATE IN ('CA','NV','OR','WA') THEN 'America/Los_Angeles'
        WHEN STATE = 'AK' THEN 'America/Anchorage'
        WHEN STATE = 'HI' THEN 'Pacific/Honolulu'
        ELSE 'America/New_York'
    END AS TIMEZONE,
    CONVERT_TIMEZONE('UTC',
        CASE
            WHEN STATE IN ('CT','DC','DE','FL','GA','IN','KY','MA','MD','ME','MI','NC','NH','NJ','NY','OH','PA','RI','SC','VA','VT','WV') THEN 'America/New_York'
            WHEN STATE IN ('AL','AR','IA','IL','KS','LA','MN','MO','MS','ND','NE','OK','SD','TN','TX','WI') THEN 'America/Chicago'
            WHEN STATE IN ('AZ','CO','ID','MT','NM','UT','WY') THEN 'America/Denver'
            WHEN STATE IN ('CA','NV','OR','WA') THEN 'America/Los_Angeles'
            WHEN STATE = 'AK' THEN 'America/Anchorage'
            WHEN STATE = 'HI' THEN 'Pacific/Honolulu'
            ELSE 'America/New_York'
        END,
        TRANS_DATE_TRANS_TIME
    ) AS LOCAL_TRANS_TIME,
    HOUR(CONVERT_TIMEZONE('UTC',
        CASE
            WHEN STATE IN ('CT','DC','DE','FL','GA','IN','KY','MA','MD','ME','MI','NC','NH','NJ','NY','OH','PA','RI','SC','VA','VT','WV') THEN 'America/New_York'
            WHEN STATE IN ('AL','AR','IA','IL','KS','LA','MN','MO','MS','ND','NE','OK','SD','TN','TX','WI') THEN 'America/Chicago'
            WHEN STATE IN ('AZ','CO','ID','MT','NM','UT','WY') THEN 'America/Denver'
            WHEN STATE IN ('CA','NV','OR','WA') THEN 'America/Los_Angeles'
            WHEN STATE = 'AK' THEN 'America/Anchorage'
            WHEN STATE = 'HI' THEN 'Pacific/Honolulu'
            ELSE 'America/New_York'
        END,
        TRANS_DATE_TRANS_TIME
    )) AS LOCAL_HOUR
FROM KAGGLE_DB.BRONZE.RAW_TRANSACTIONS;

-- Add score columns
ALTER TABLE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS ADD COLUMN VELOCITY_SCORE FLOAT;
ALTER TABLE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS ADD COLUMN LOCATION_SCORE FLOAT;
ALTER TABLE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS ADD COLUMN AMOUNT_SCORE FLOAT;
ALTER TABLE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS ADD COLUMN MERCHANT_SCORE FLOAT;
ALTER TABLE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS ADD COLUMN RISK_SCORE FLOAT;

-- Compute velocity score
UPDATE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS t
SET VELOCITY_SCORE = v.VS
FROM (
    SELECT ID, LEAST((COUNT(*) OVER (PARTITION BY CC_NUM ORDER BY TRANS_DATE_TRANS_TIME RANGE BETWEEN INTERVAL '24 HOURS' PRECEDING AND CURRENT ROW) - 1) / 10.0, 1.0) AS VS
    FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
) v WHERE t.ID = v.ID;

-- Compute location score
UPDATE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS t
SET LOCATION_SCORE = ls.LS
FROM (
    SELECT ID, LEAST(CASE WHEN AVG(DISTANCE_KM) OVER (PARTITION BY CC_NUM) = 0 THEN 0 ELSE DISTANCE_KM / (AVG(DISTANCE_KM) OVER (PARTITION BY CC_NUM) * 3) END, 1.0) AS LS
    FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
) ls WHERE t.ID = ls.ID;

-- Compute amount score
UPDATE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS t
SET AMOUNT_SCORE = a.AMS
FROM (
    SELECT ID, LEAST(CASE WHEN STDDEV(AMT) OVER (PARTITION BY CC_NUM) = 0 OR STDDEV(AMT) OVER (PARTITION BY CC_NUM) IS NULL
        THEN CASE WHEN AMT > 500 THEN 1.0 ELSE AMT / 500.0 END
        ELSE ABS(AMT - AVG(AMT) OVER (PARTITION BY CC_NUM)) / (STDDEV(AMT) OVER (PARTITION BY CC_NUM) * 3) END, 1.0) AS AMS
    FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
) a WHERE t.ID = a.ID;

-- Compute merchant score
UPDATE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS t
SET MERCHANT_SCORE = ms.SCORE
FROM (
    SELECT MERCHANT, LEAST(SUM(IS_FRAUD) * 1.0 / COUNT(*) / 0.02, 1.0) AS SCORE
    FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
    GROUP BY MERCHANT
) ms WHERE t.MERCHANT = ms.MERCHANT;

-- Compute composite risk score
UPDATE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
SET RISK_SCORE = ROUND((AMOUNT_SCORE * 0.40) + (VELOCITY_SCORE * 0.35) + (LOCATION_SCORE * 0.25), 4);

ALTER TABLE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS SET CHANGE_TRACKING = TRUE;
