-- ============================================
-- 06: STREAMS, TASKS & ALERTS
-- ============================================

-- Streams (CDC)
CREATE OR REPLACE STREAM KAGGLE_DB.BRONZE.STM_RAW_TRANSACTIONS
ON TABLE KAGGLE_DB.BRONZE.RAW_TRANSACTIONS;

CREATE OR REPLACE STREAM KAGGLE_DB.SILVER.STM_ENRICHED_TRANSACTIONS
ON TABLE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS;

-- Fraud Alerts Table
CREATE OR REPLACE TABLE KAGGLE_DB.FRAUD_ANALYSIS.FRAUD_ALERTS (
    ALERT_ID NUMBER AUTOINCREMENT,
    ALERT_TYPE VARCHAR(50),
    CC_NUM VARCHAR,
    MERCHANT VARCHAR,
    TRANSACTION_ID NUMBER,
    AMT FLOAT,
    RISK_SCORE FLOAT,
    MERCHANT_SCORE FLOAT,
    ALERT_REASON VARCHAR(500),
    ALERT_SEVERITY VARCHAR(20),
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_RESOLVED BOOLEAN DEFAULT FALSE
);

-- Tasks (DAG: parent → child)
CREATE OR REPLACE TASK KAGGLE_DB.FRAUD_ANALYSIS.TASK_BRONZE_TO_SILVER
    WAREHOUSE = FRAUD_TASK_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('KAGGLE_DB.BRONZE.STM_RAW_TRANSACTIONS')
AS
    CALL KAGGLE_DB.SILVER.SP_BRONZE_TO_SILVER();

CREATE OR REPLACE TASK KAGGLE_DB.FRAUD_ANALYSIS.TASK_SILVER_TO_GOLD
    WAREHOUSE = FRAUD_TASK_WH
    AFTER KAGGLE_DB.FRAUD_ANALYSIS.TASK_BRONZE_TO_SILVER
AS
    CALL KAGGLE_DB.GOLD.SP_SILVER_TO_GOLD();

-- Alerts
CREATE OR REPLACE ALERT KAGGLE_DB.FRAUD_ANALYSIS.ALERT_RAPID_FIRE_FRAUD
    WAREHOUSE = FRAUD_TASK_WH
    SCHEDULE = '5 MINUTE'
    IF (EXISTS (
        SELECT 1 FROM (
            SELECT CC_NUM, COUNT(*) OVER (PARTITION BY CC_NUM ORDER BY TRANS_DATE_TRANS_TIME RANGE BETWEEN INTERVAL '5 MINUTES' PRECEDING AND CURRENT ROW) AS txn_count
            FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
            WHERE TRANS_DATE_TRANS_TIME >= DATEADD('MINUTE', -6, CURRENT_TIMESTAMP())
        ) WHERE txn_count >= 2
    ))
    THEN CALL KAGGLE_DB.FRAUD_ANALYSIS.SP_DETECT_RAPID_FIRE_FRAUD();

CREATE OR REPLACE ALERT KAGGLE_DB.FRAUD_ANALYSIS.ALERT_HIGH_RISK_MERCHANT
    WAREHOUSE = FRAUD_TASK_WH
    SCHEDULE = '5 MINUTE'
    IF (EXISTS (
        SELECT 1 FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
        WHERE TRANS_DATE_TRANS_TIME >= DATEADD('MINUTE', -6, CURRENT_TIMESTAMP())
            AND MERCHANT_SCORE >= 0.8 AND AMT > 200
            AND ID NOT IN (SELECT TRANSACTION_ID FROM KAGGLE_DB.FRAUD_ANALYSIS.FRAUD_ALERTS WHERE ALERT_TYPE = 'HIGH_RISK_MERCHANT')
    ))
    THEN
        INSERT INTO KAGGLE_DB.FRAUD_ANALYSIS.FRAUD_ALERTS 
            (ALERT_TYPE, CC_NUM, MERCHANT, TRANSACTION_ID, AMT, RISK_SCORE, MERCHANT_SCORE, ALERT_REASON, ALERT_SEVERITY)
        SELECT 'HIGH_RISK_MERCHANT', CC_NUM, MERCHANT, ID, AMT, RISK_SCORE, MERCHANT_SCORE,
            'High-risk merchant (score: ' || ROUND(MERCHANT_SCORE, 2) || ') with large amount ($' || ROUND(AMT, 2) || ')', 'CRITICAL'
        FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
        WHERE TRANS_DATE_TRANS_TIME >= DATEADD('MINUTE', -6, CURRENT_TIMESTAMP())
            AND MERCHANT_SCORE >= 0.8 AND AMT > 200
            AND ID NOT IN (SELECT TRANSACTION_ID FROM KAGGLE_DB.FRAUD_ANALYSIS.FRAUD_ALERTS WHERE ALERT_TYPE = 'HIGH_RISK_MERCHANT');

CREATE OR REPLACE ALERT KAGGLE_DB.FRAUD_ANALYSIS.ALERT_SCHEMA_DRIFT
    WAREHOUSE = FRAUD_TASK_WH
    SCHEDULE = '360 MINUTE'
    IF (EXISTS (
        SELECT 1 FROM KAGGLE_DB.INFORMATION_SCHEMA.COLUMNS b
        WHERE b.TABLE_SCHEMA = 'BRONZE' AND b.TABLE_NAME = 'RAW_TRANSACTIONS'
        AND b.COLUMN_NAME NOT IN (
            SELECT COLUMN_NAME FROM KAGGLE_DB.INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = 'SILVER' AND TABLE_NAME = 'ENRICHED_TRANSACTIONS'
        )
    ))
    THEN CALL KAGGLE_DB.BRONZE.SP_SCHEMA_CHECKPOINT();

-- Resume all (child first, then parent)
ALTER TASK KAGGLE_DB.FRAUD_ANALYSIS.TASK_SILVER_TO_GOLD RESUME;
ALTER TASK KAGGLE_DB.FRAUD_ANALYSIS.TASK_BRONZE_TO_SILVER RESUME;
ALTER ALERT KAGGLE_DB.FRAUD_ANALYSIS.ALERT_RAPID_FIRE_FRAUD RESUME;
ALTER ALERT KAGGLE_DB.FRAUD_ANALYSIS.ALERT_HIGH_RISK_MERCHANT RESUME;
ALTER ALERT KAGGLE_DB.FRAUD_ANALYSIS.ALERT_SCHEMA_DRIFT RESUME;

-- Required privileges
GRANT EXECUTE TASK ON ACCOUNT TO ROLE SYSADMIN;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE SYSADMIN;
