-- ============================================
-- 07: POWER BI VIEWS
-- ============================================

-- Dimension Views
CREATE OR REPLACE VIEW KAGGLE_DB.GOLD.VW_PBI_DIM_DATE AS SELECT * FROM KAGGLE_DB.GOLD.DIM_DATE;

CREATE OR REPLACE VIEW KAGGLE_DB.GOLD.VW_PBI_DIM_CUSTOMER AS
SELECT 
    CUSTOMER_SK,
    LEFT(CC_NUM, 4) || '****' || RIGHT(CC_NUM, 4) AS CC_NUM_MASKED,
    FIRST,
    LAST,
    GENDER,
    DOB,
    JOB,
    AGE
FROM KAGGLE_DB.GOLD.DIM_CUSTOMER;

CREATE OR REPLACE VIEW KAGGLE_DB.GOLD.VW_PBI_DIM_MERCHANT AS SELECT * FROM KAGGLE_DB.GOLD.DIM_MERCHANT;
CREATE OR REPLACE VIEW KAGGLE_DB.GOLD.VW_PBI_DIM_LOCATION AS SELECT * FROM KAGGLE_DB.GOLD.DIM_LOCATION;
CREATE OR REPLACE VIEW KAGGLE_DB.GOLD.VW_PBI_DIM_TIME_SLOT AS SELECT * FROM KAGGLE_DB.GOLD.DIM_TIME_SLOT;
CREATE OR REPLACE VIEW KAGGLE_DB.GOLD.VW_PBI_DIM_AMOUNT_BUCKET AS SELECT * FROM KAGGLE_DB.GOLD.DIM_AMOUNT_BUCKET;
CREATE OR REPLACE VIEW KAGGLE_DB.GOLD.VW_PBI_DIM_AGE_BUCKET AS SELECT * FROM KAGGLE_DB.GOLD.DIM_AGE_BUCKET;
CREATE OR REPLACE VIEW KAGGLE_DB.GOLD.VW_PBI_DIM_RISK_BAND AS SELECT * FROM KAGGLE_DB.GOLD.DIM_RISK_BAND;
CREATE OR REPLACE VIEW KAGGLE_DB.GOLD.VW_PBI_DIM_TIMEZONE AS SELECT * FROM KAGGLE_DB.GOLD.DIM_TIMEZONE;

-- Fact View
CREATE OR REPLACE VIEW KAGGLE_DB.GOLD.VW_PBI_FACT_TRANSACTIONS AS
SELECT 
    f.TRANSACTION_ID, f.TRANS_NUM, f.CUSTOMER_SK, f.MERCHANT_SK, f.LOCATION_SK,
    f.DATE_SK, f.TIME_SLOT_SK, f.AMOUNT_BUCKET_SK, f.AGE_BUCKET_SK,
    f.RISK_BAND_SK, f.TIMEZONE_SK,
    f.TRANS_DATE_TRANS_TIME, f.LOCAL_TRANS_TIME, f.AMT, f.DISTANCE_KM, f.IS_FRAUD,
    f.VELOCITY_SCORE, f.LOCATION_SCORE, f.AMOUNT_SCORE, f.RISK_SCORE
FROM KAGGLE_DB.GOLD.FACT_TRANSACTIONS f;

-- Pre-aggregated Views (for static KPIs)
CREATE OR REPLACE VIEW KAGGLE_DB.GOLD.VW_PBI_EXEC_SUMMARY AS
SELECT 
    COUNT(*) AS TOTAL_TRANSACTIONS,
    SUM(IS_FRAUD) AS TOTAL_FRAUDS,
    ROUND(SUM(IS_FRAUD)*100.0/COUNT(*), 2) AS FRAUD_RATE_PCT,
    ROUND(SUM(CASE WHEN IS_FRAUD=1 THEN AMT ELSE 0 END), 2) AS TOTAL_FRAUD_LOSS,
    ROUND(AVG(CASE WHEN IS_FRAUD=1 THEN AMT END), 2) AS AVG_FRAUD_AMOUNT,
    COUNT(DISTINCT CASE WHEN IS_FRAUD=1 THEN CUSTOMER_SK END) AS AFFECTED_CUSTOMERS
FROM KAGGLE_DB.GOLD.FACT_TRANSACTIONS;

CREATE OR REPLACE VIEW KAGGLE_DB.GOLD.VW_PBI_MONTHLY_TREND AS
SELECT 
    d.YEAR, d.MONTH, d.MONTH_NAME,
    COUNT(*) AS TOTAL_TXNS,
    SUM(f.IS_FRAUD) AS FRAUD_COUNT,
    ROUND(SUM(f.IS_FRAUD)*100.0/COUNT(*), 2) AS FRAUD_RATE_PCT,
    ROUND(SUM(CASE WHEN f.IS_FRAUD=1 THEN f.AMT ELSE 0 END), 2) AS FRAUD_LOSS
FROM KAGGLE_DB.GOLD.FACT_TRANSACTIONS f
JOIN KAGGLE_DB.GOLD.DIM_DATE d ON f.DATE_SK = d.DATE_SK
GROUP BY d.YEAR, d.MONTH, d.MONTH_NAME;

-- Fraud Alerts View
CREATE OR REPLACE VIEW KAGGLE_DB.GOLD.VW_PBI_FRAUD_ALERTS AS
SELECT * FROM KAGGLE_DB.FRAUD_ANALYSIS.FRAUD_ALERTS;

-- Warehouse Setup
CREATE WAREHOUSE IF NOT EXISTS FRAUD_TASK_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

ALTER WAREHOUSE COMPUTE_WH SET AUTO_SUSPEND = 60;
