-- ============================================
-- 08: DATA GOVERNANCE (Masking Policies for PII)
-- ============================================

CREATE SCHEMA IF NOT EXISTS KAGGLE_DB.GOVERNANCE;

-- String masking (CC_NUM, names, address, job)
CREATE OR REPLACE MASKING POLICY KAGGLE_DB.GOVERNANCE.MASK_PII_STRING AS
(val STRING) RETURNS STRING ->
    CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN') THEN val
    ELSE '***MASKED***'
    END;

-- Number masking (ZIP)
CREATE OR REPLACE MASKING POLICY KAGGLE_DB.GOVERNANCE.MASK_PII_NUMBER AS
(val NUMBER) RETURNS NUMBER ->
    CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN') THEN val
    ELSE 0
    END;

-- Float masking (LAT, LONG, MERCH_LAT, MERCH_LONG)
CREATE OR REPLACE MASKING POLICY KAGGLE_DB.GOVERNANCE.MASK_PII_FLOAT AS
(val FLOAT) RETURNS FLOAT ->
    CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN') THEN val
    ELSE 0.0
    END;

-- Date masking (DOB)
CREATE OR REPLACE MASKING POLICY KAGGLE_DB.GOVERNANCE.MASK_PII_DATE AS
(val DATE) RETURNS DATE ->
    CASE WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN') THEN val
    ELSE '1900-01-01'::DATE
    END;

-- Apply to Bronze table (PII columns)
ALTER TABLE KAGGLE_DB.BRONZE.RAW_TRANSACTIONS MODIFY COLUMN CC_NUM SET MASKING POLICY KAGGLE_DB.GOVERNANCE.MASK_PII_STRING;
ALTER TABLE KAGGLE_DB.BRONZE.RAW_TRANSACTIONS MODIFY COLUMN FIRST SET MASKING POLICY KAGGLE_DB.GOVERNANCE.MASK_PII_STRING;
ALTER TABLE KAGGLE_DB.BRONZE.RAW_TRANSACTIONS MODIFY COLUMN LAST SET MASKING POLICY KAGGLE_DB.GOVERNANCE.MASK_PII_STRING;
ALTER TABLE KAGGLE_DB.BRONZE.RAW_TRANSACTIONS MODIFY COLUMN GENDER SET MASKING POLICY KAGGLE_DB.GOVERNANCE.MASK_PII_STRING;
ALTER TABLE KAGGLE_DB.BRONZE.RAW_TRANSACTIONS MODIFY COLUMN STREET SET MASKING POLICY KAGGLE_DB.GOVERNANCE.MASK_PII_STRING;
ALTER TABLE KAGGLE_DB.BRONZE.RAW_TRANSACTIONS MODIFY COLUMN DOB SET MASKING POLICY KAGGLE_DB.GOVERNANCE.MASK_PII_DATE;
ALTER TABLE KAGGLE_DB.BRONZE.RAW_TRANSACTIONS MODIFY COLUMN ZIP SET MASKING POLICY KAGGLE_DB.GOVERNANCE.MASK_PII_NUMBER;
ALTER TABLE KAGGLE_DB.BRONZE.RAW_TRANSACTIONS MODIFY COLUMN LAT SET MASKING POLICY KAGGLE_DB.GOVERNANCE.MASK_PII_FLOAT;
ALTER TABLE KAGGLE_DB.BRONZE.RAW_TRANSACTIONS MODIFY COLUMN LONG SET MASKING POLICY KAGGLE_DB.GOVERNANCE.MASK_PII_FLOAT;
