-- ============================================
-- 04: GOLD LAYER (Star Schema)
-- ============================================

-- DIM_CUSTOMER
CREATE OR REPLACE TABLE KAGGLE_DB.GOLD.DIM_CUSTOMER AS
SELECT
    ROW_NUMBER() OVER (ORDER BY CC_NUM) AS CUSTOMER_SK,
    CC_NUM, FIRST, LAST, GENDER, DOB, JOB,
    DATEDIFF('YEAR', DOB, CURRENT_DATE()) AS AGE
FROM (
    SELECT DISTINCT CC_NUM, FIRST, LAST, GENDER, DOB, JOB
    FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
);

-- DIM_MERCHANT
CREATE OR REPLACE TABLE KAGGLE_DB.GOLD.DIM_MERCHANT AS
SELECT
    ROW_NUMBER() OVER (ORDER BY MERCHANT, CATEGORY) AS MERCHANT_SK,
    MERCHANT,
    CATEGORY,
    ROUND(AVG(MERCH_LAT), 4) AS AVG_MERCH_LAT,
    ROUND(AVG(MERCH_LONG), 4) AS AVG_MERCH_LONG,
    COUNT(*) AS TRANSACTION_COUNT,
    LEAST(SUM(IS_FRAUD) * 1.0 / COUNT(*) / 0.02, 1.0) AS MERCHANT_SCORE,
    CASE
        WHEN CATEGORY IN ('shopping_net', 'misc_net') THEN 'Online'
        WHEN CATEGORY IN ('shopping_pos', 'misc_pos', 'grocery_pos') THEN 'In-Store'
        WHEN CATEGORY IN ('food_dining', 'gas_transport') THEN 'Food & Gas'
        WHEN CATEGORY IN ('entertainment', 'travel', 'health_fitness', 'personal_care') THEN 'Lifestyle'
        WHEN CATEGORY IN ('home', 'kids_pets', 'grocery_net') THEN 'Home & Family'
        ELSE 'Other'
    END AS CATEGORY_BUCKET
FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
GROUP BY MERCHANT, CATEGORY;

-- DIM_LOCATION
CREATE OR REPLACE TABLE KAGGLE_DB.GOLD.DIM_LOCATION AS
SELECT
    ROW_NUMBER() OVER (ORDER BY STATE, CITY, ZIP) AS LOCATION_SK,
    CITY, STATE, ZIP, LAT, LONG, CITY_POP
FROM (
    SELECT DISTINCT CITY, STATE, ZIP, LAT, LONG, CITY_POP
    FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
);

-- DIM_DATE
CREATE OR REPLACE TABLE KAGGLE_DB.GOLD.DIM_DATE AS
SELECT
    ROW_NUMBER() OVER (ORDER BY DATE_KEY) AS DATE_SK,
    DATE_KEY, YEAR, MONTH, MONTH_NAME, DAY_OF_MONTH, DAY_NAME, DAY_OF_WEEK, QUARTER, WEEK_OF_YEAR
FROM (
    SELECT DISTINCT
        DATE(TRANS_DATE_TRANS_TIME) AS DATE_KEY,
        YEAR(TRANS_DATE_TRANS_TIME) AS YEAR,
        MONTH(TRANS_DATE_TRANS_TIME) AS MONTH,
        MONTHNAME(TRANS_DATE_TRANS_TIME) AS MONTH_NAME,
        DAY(TRANS_DATE_TRANS_TIME) AS DAY_OF_MONTH,
        DAYNAME(TRANS_DATE_TRANS_TIME) AS DAY_NAME,
        DAYOFWEEK(TRANS_DATE_TRANS_TIME) AS DAY_OF_WEEK,
        QUARTER(TRANS_DATE_TRANS_TIME) AS QUARTER,
        WEEKOFYEAR(TRANS_DATE_TRANS_TIME) AS WEEK_OF_YEAR
    FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
);

-- DIM_TIME_SLOT
CREATE OR REPLACE TABLE KAGGLE_DB.GOLD.DIM_TIME_SLOT (
    TIME_SLOT_SK NUMBER AUTOINCREMENT,
    HOUR_OF_DAY NUMBER,
    TIME_OF_DAY VARCHAR(15),
    IS_BUSINESS_HOURS BOOLEAN,
    SLOT_ORDER NUMBER
);
INSERT INTO KAGGLE_DB.GOLD.DIM_TIME_SLOT (HOUR_OF_DAY, TIME_OF_DAY, IS_BUSINESS_HOURS, SLOT_ORDER)
SELECT
    h.VALUE::INT,
    CASE WHEN h.VALUE::INT BETWEEN 0 AND 5 THEN 'LATE_NIGHT'
         WHEN h.VALUE::INT BETWEEN 6 AND 11 THEN 'MORNING'
         WHEN h.VALUE::INT BETWEEN 12 AND 17 THEN 'AFTERNOON'
         ELSE 'EVENING' END,
    h.VALUE::INT BETWEEN 9 AND 17,
    h.VALUE::INT
FROM TABLE(FLATTEN(ARRAY_GENERATE_RANGE(0, 24))) h;

-- DIM_AMOUNT_BUCKET
CREATE OR REPLACE TABLE KAGGLE_DB.GOLD.DIM_AMOUNT_BUCKET (
    AMOUNT_BUCKET_SK NUMBER AUTOINCREMENT,
    AMOUNT_BUCKET VARCHAR(15),
    AMT_MIN FLOAT,
    AMT_MAX FLOAT,
    BUCKET_ORDER NUMBER
);
INSERT INTO KAGGLE_DB.GOLD.DIM_AMOUNT_BUCKET (AMOUNT_BUCKET, AMT_MIN, AMT_MAX, BUCKET_ORDER) VALUES
('MICRO', 0, 9.99, 1),
('SMALL', 10, 49.99, 2),
('MEDIUM', 50, 199.99, 3),
('LARGE', 200, 499.99, 4),
('VERY_LARGE', 500, 99999, 5);

-- DIM_AGE_BUCKET
CREATE OR REPLACE TABLE KAGGLE_DB.GOLD.DIM_AGE_BUCKET (
    AGE_BUCKET_SK NUMBER AUTOINCREMENT,
    AGE_GROUP VARCHAR(10),
    AGE_MIN NUMBER,
    AGE_MAX NUMBER,
    GENERATION VARCHAR(20)
);
INSERT INTO KAGGLE_DB.GOLD.DIM_AGE_BUCKET (AGE_GROUP, AGE_MIN, AGE_MAX, GENERATION) VALUES
('Under 18', 0, 17, 'Gen Z'),
('18-24', 18, 24, 'Gen Z'),
('25-34', 25, 34, 'Millennial'),
('35-44', 35, 44, 'Millennial'),
('45-54', 45, 54, 'Gen X'),
('55-64', 55, 64, 'Boomer'),
('65+', 65, 120, 'Boomer');

-- DIM_RISK_BAND
CREATE OR REPLACE TABLE KAGGLE_DB.GOLD.DIM_RISK_BAND (
    RISK_BAND_SK NUMBER AUTOINCREMENT,
    RISK_BAND VARCHAR(20),
    RISK_MIN FLOAT,
    RISK_MAX FLOAT,
    BAND_ORDER NUMBER,
    ACTION_REQUIRED VARCHAR(50)
);
INSERT INTO KAGGLE_DB.GOLD.DIM_RISK_BAND (RISK_BAND, RISK_MIN, RISK_MAX, BAND_ORDER, ACTION_REQUIRED) VALUES
('LOW', 0, 0.2, 1, 'No action'),
('MODERATE', 0.2, 0.4, 2, 'Monitor'),
('HIGH', 0.4, 0.6, 3, 'Flag for review'),
('VERY HIGH', 0.6, 0.8, 4, 'Hold & verify'),
('CRITICAL', 0.8, 1.0, 5, 'Block & investigate');

-- DIM_TIMEZONE
CREATE OR REPLACE TABLE KAGGLE_DB.GOLD.DIM_TIMEZONE (
    TIMEZONE_SK NUMBER AUTOINCREMENT,
    TIMEZONE_NAME VARCHAR(30),
    UTC_OFFSET VARCHAR(10),
    ABBREVIATION VARCHAR(5),
    REGION VARCHAR(20)
);
INSERT INTO KAGGLE_DB.GOLD.DIM_TIMEZONE (TIMEZONE_NAME, UTC_OFFSET, ABBREVIATION, REGION) VALUES
('America/New_York', 'UTC-5', 'EST', 'Eastern'),
('America/Chicago', 'UTC-6', 'CST', 'Central'),
('America/Denver', 'UTC-7', 'MST', 'Mountain'),
('America/Los_Angeles', 'UTC-8', 'PST', 'Pacific'),
('America/Anchorage', 'UTC-9', 'AKST', 'Alaska'),
('Pacific/Honolulu', 'UTC-10', 'HST', 'Hawaii');

-- FACT_TRANSACTIONS
CREATE OR REPLACE TABLE KAGGLE_DB.GOLD.FACT_TRANSACTIONS AS
SELECT
    t.ID AS TRANSACTION_ID,
    t.TRANS_NUM,
    c.CUSTOMER_SK,
    m.MERCHANT_SK,
    l.LOCATION_SK,
    d.DATE_SK,
    ts.TIME_SLOT_SK,
    ab.AMOUNT_BUCKET_SK,
    ag.AGE_BUCKET_SK,
    rb.RISK_BAND_SK,
    tz.TIMEZONE_SK,
    t.TRANS_DATE_TRANS_TIME,
    t.LOCAL_TRANS_TIME,
    t.AMT,
    t.DISTANCE_KM,
    t.IS_FRAUD,
    t.VELOCITY_SCORE,
    t.LOCATION_SCORE,
    t.AMOUNT_SCORE,
    t.RISK_SCORE
FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS t
LEFT JOIN KAGGLE_DB.GOLD.DIM_CUSTOMER c ON t.CC_NUM = c.CC_NUM
LEFT JOIN KAGGLE_DB.GOLD.DIM_MERCHANT m ON t.MERCHANT = m.MERCHANT AND t.CATEGORY = m.CATEGORY
LEFT JOIN KAGGLE_DB.GOLD.DIM_LOCATION l ON t.CITY = l.CITY AND t.STATE = l.STATE AND t.ZIP = l.ZIP
LEFT JOIN KAGGLE_DB.GOLD.DIM_DATE d ON DATE(t.TRANS_DATE_TRANS_TIME) = d.DATE_KEY
LEFT JOIN KAGGLE_DB.GOLD.DIM_TIME_SLOT ts ON t.LOCAL_HOUR = ts.HOUR_OF_DAY
LEFT JOIN KAGGLE_DB.GOLD.DIM_AMOUNT_BUCKET ab ON t.AMOUNT_BUCKET = ab.AMOUNT_BUCKET
LEFT JOIN KAGGLE_DB.GOLD.DIM_AGE_BUCKET ag ON t.AGE >= ag.AGE_MIN AND t.AGE <= ag.AGE_MAX
LEFT JOIN KAGGLE_DB.GOLD.DIM_RISK_BAND rb ON t.RISK_SCORE >= rb.RISK_MIN AND t.RISK_SCORE < rb.RISK_MAX
LEFT JOIN KAGGLE_DB.GOLD.DIM_TIMEZONE tz ON t.TIMEZONE = tz.TIMEZONE_NAME;

ALTER TABLE KAGGLE_DB.GOLD.FACT_TRANSACTIONS CLUSTER BY (DATE_SK, CUSTOMER_SK);
