-- ============================================
-- 05: STORED PROCEDURES (Error Handling + Logging)
-- ============================================

-- Bronze to Silver (with timezone, scoring, execution logging)
CREATE OR REPLACE PROCEDURE KAGGLE_DB.SILVER.SP_BRONZE_TO_SILVER()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    error_msg VARCHAR;
    v_start TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP();
BEGIN
    IF (NOT SYSTEM$STREAM_HAS_DATA('KAGGLE_DB.BRONZE.STM_RAW_TRANSACTIONS')) THEN
        INSERT INTO KAGGLE_DB.BRONZE.PIPELINE_EXECUTION_LOG 
            (PROCEDURE_NAME, EXECUTION_STATUS, START_TIME, END_TIME, DURATION_SECONDS, ROWS_PROCESSED, BATCH_TIMESTAMP, WAREHOUSE_NAME)
        VALUES ('SP_BRONZE_TO_SILVER', 'SKIPPED', :v_start, CURRENT_TIMESTAMP(), 0, 0, CURRENT_TIMESTAMP(), CURRENT_WAREHOUSE());
        RETURN 'No new data in stream. Skipping.';
    END IF;

    MERGE INTO KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS AS tgt
    USING (
        SELECT
            ID, TRANS_DATE_TRANS_TIME, CC_NUM, MERCHANT, CATEGORY, AMT,
            FIRST, LAST, GENDER, STREET, CITY, STATE, ZIP,
            LAT, LONG, CITY_POP, JOB, DOB, TRANS_NUM, UNIX_TIME,
            MERCH_LAT, MERCH_LONG, IS_FRAUD, INGESTED_AT,
            DATEDIFF('YEAR', DOB, TRANS_DATE_TRANS_TIME) AS AGE,
            HOUR(TRANS_DATE_TRANS_TIME) AS TRANSACTION_HOUR,
            DAYNAME(TRANS_DATE_TRANS_TIME) AS TRANSACTION_DAY,
            DATE_TRUNC('MONTH', TRANS_DATE_TRANS_TIME) AS TRANSACTION_MONTH,
            CASE WHEN AMT < 10 THEN 'MICRO' WHEN AMT < 50 THEN 'SMALL' WHEN AMT < 200 THEN 'MEDIUM' WHEN AMT < 500 THEN 'LARGE' ELSE 'VERY_LARGE' END AS AMOUNT_BUCKET,
            HAVERSINE(LAT, LONG, MERCH_LAT, MERCH_LONG) AS DISTANCE_KM,
            CASE WHEN HOUR(TRANS_DATE_TRANS_TIME) BETWEEN 0 AND 5 THEN 'LATE_NIGHT' WHEN HOUR(TRANS_DATE_TRANS_TIME) BETWEEN 6 AND 11 THEN 'MORNING' WHEN HOUR(TRANS_DATE_TRANS_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON' ELSE 'EVENING' END AS TIME_OF_DAY,
            CASE
                WHEN STATE IN ('CT','DC','DE','FL','GA','IN','KY','MA','MD','ME','MI','NC','NH','NJ','NY','OH','PA','RI','SC','VA','VT','WV') THEN 'America/New_York'
                WHEN STATE IN ('AL','AR','IA','IL','KS','LA','MN','MO','MS','ND','NE','OK','SD','TN','TX','WI') THEN 'America/Chicago'
                WHEN STATE IN ('AZ','CO','ID','MT','NM','UT','WY') THEN 'America/Denver'
                WHEN STATE IN ('CA','NV','OR','WA') THEN 'America/Los_Angeles'
                WHEN STATE = 'AK' THEN 'America/Anchorage'
                WHEN STATE = 'HI' THEN 'Pacific/Honolulu'
                ELSE 'America/New_York'
            END AS TIMEZONE,
            CONVERT_TIMEZONE('UTC', CASE
                WHEN STATE IN ('CT','DC','DE','FL','GA','IN','KY','MA','MD','ME','MI','NC','NH','NJ','NY','OH','PA','RI','SC','VA','VT','WV') THEN 'America/New_York'
                WHEN STATE IN ('AL','AR','IA','IL','KS','LA','MN','MO','MS','ND','NE','OK','SD','TN','TX','WI') THEN 'America/Chicago'
                WHEN STATE IN ('AZ','CO','ID','MT','NM','UT','WY') THEN 'America/Denver'
                WHEN STATE IN ('CA','NV','OR','WA') THEN 'America/Los_Angeles'
                WHEN STATE = 'AK' THEN 'America/Anchorage'
                WHEN STATE = 'HI' THEN 'Pacific/Honolulu'
                ELSE 'America/New_York'
            END, TRANS_DATE_TRANS_TIME) AS LOCAL_TRANS_TIME,
            HOUR(CONVERT_TIMEZONE('UTC', CASE
                WHEN STATE IN ('CT','DC','DE','FL','GA','IN','KY','MA','MD','ME','MI','NC','NH','NJ','NY','OH','PA','RI','SC','VA','VT','WV') THEN 'America/New_York'
                WHEN STATE IN ('AL','AR','IA','IL','KS','LA','MN','MO','MS','ND','NE','OK','SD','TN','TX','WI') THEN 'America/Chicago'
                WHEN STATE IN ('AZ','CO','ID','MT','NM','UT','WY') THEN 'America/Denver'
                WHEN STATE IN ('CA','NV','OR','WA') THEN 'America/Los_Angeles'
                WHEN STATE = 'AK' THEN 'America/Anchorage'
                WHEN STATE = 'HI' THEN 'Pacific/Honolulu'
                ELSE 'America/New_York'
            END, TRANS_DATE_TRANS_TIME)) AS LOCAL_HOUR
        FROM KAGGLE_DB.BRONZE.STM_RAW_TRANSACTIONS
        WHERE METADATA$ACTION = 'INSERT'
    ) AS src
    ON tgt.ID = src.ID
    WHEN MATCHED THEN UPDATE SET
        tgt.TRANS_DATE_TRANS_TIME = src.TRANS_DATE_TRANS_TIME, tgt.CC_NUM = src.CC_NUM,
        tgt.MERCHANT = src.MERCHANT, tgt.CATEGORY = src.CATEGORY, tgt.AMT = src.AMT,
        tgt.FIRST = src.FIRST, tgt.LAST = src.LAST, tgt.GENDER = src.GENDER,
        tgt.STREET = src.STREET, tgt.CITY = src.CITY, tgt.STATE = src.STATE, tgt.ZIP = src.ZIP,
        tgt.LAT = src.LAT, tgt.LONG = src.LONG, tgt.CITY_POP = src.CITY_POP,
        tgt.JOB = src.JOB, tgt.DOB = src.DOB, tgt.TRANS_NUM = src.TRANS_NUM,
        tgt.UNIX_TIME = src.UNIX_TIME, tgt.MERCH_LAT = src.MERCH_LAT, tgt.MERCH_LONG = src.MERCH_LONG,
        tgt.IS_FRAUD = src.IS_FRAUD, tgt.INGESTED_AT = src.INGESTED_AT,
        tgt.AGE = src.AGE, tgt.TRANSACTION_HOUR = src.TRANSACTION_HOUR,
        tgt.TRANSACTION_DAY = src.TRANSACTION_DAY, tgt.TRANSACTION_MONTH = src.TRANSACTION_MONTH,
        tgt.AMOUNT_BUCKET = src.AMOUNT_BUCKET, tgt.DISTANCE_KM = src.DISTANCE_KM,
        tgt.TIME_OF_DAY = src.TIME_OF_DAY, tgt.TIMEZONE = src.TIMEZONE,
        tgt.LOCAL_TRANS_TIME = src.LOCAL_TRANS_TIME, tgt.LOCAL_HOUR = src.LOCAL_HOUR
    WHEN NOT MATCHED THEN INSERT (
        ID, TRANS_DATE_TRANS_TIME, CC_NUM, MERCHANT, CATEGORY, AMT,
        FIRST, LAST, GENDER, STREET, CITY, STATE, ZIP,
        LAT, LONG, CITY_POP, JOB, DOB, TRANS_NUM, UNIX_TIME,
        MERCH_LAT, MERCH_LONG, IS_FRAUD, INGESTED_AT,
        AGE, TRANSACTION_HOUR, TRANSACTION_DAY, TRANSACTION_MONTH,
        AMOUNT_BUCKET, DISTANCE_KM, TIME_OF_DAY, TIMEZONE, LOCAL_TRANS_TIME, LOCAL_HOUR
    ) VALUES (
        src.ID, src.TRANS_DATE_TRANS_TIME, src.CC_NUM, src.MERCHANT, src.CATEGORY, src.AMT,
        src.FIRST, src.LAST, src.GENDER, src.STREET, src.CITY, src.STATE, src.ZIP,
        src.LAT, src.LONG, src.CITY_POP, src.JOB, src.DOB, src.TRANS_NUM, src.UNIX_TIME,
        src.MERCH_LAT, src.MERCH_LONG, src.IS_FRAUD, src.INGESTED_AT,
        src.AGE, src.TRANSACTION_HOUR, src.TRANSACTION_DAY, src.TRANSACTION_MONTH,
        src.AMOUNT_BUCKET, src.DISTANCE_KM, src.TIME_OF_DAY, src.TIMEZONE, src.LOCAL_TRANS_TIME, src.LOCAL_HOUR
    );

    -- Compute scores for new rows
    UPDATE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS t SET MERCHANT_SCORE = ms.SCORE
    FROM (SELECT MERCHANT, LEAST(SUM(IS_FRAUD)*1.0/COUNT(*)/0.02, 1.0) AS SCORE FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS GROUP BY MERCHANT) ms
    WHERE t.MERCHANT = ms.MERCHANT AND t.MERCHANT_SCORE IS NULL;

    UPDATE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS t SET VELOCITY_SCORE = v.VS
    FROM (SELECT ID, LEAST((COUNT(*) OVER (PARTITION BY CC_NUM ORDER BY TRANS_DATE_TRANS_TIME RANGE BETWEEN INTERVAL '24 HOURS' PRECEDING AND CURRENT ROW)-1)/10.0, 1.0) AS VS FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS WHERE VELOCITY_SCORE IS NULL) v WHERE t.ID = v.ID;

    UPDATE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS t SET LOCATION_SCORE = ls.LS
    FROM (SELECT ID, LEAST(CASE WHEN AVG(DISTANCE_KM) OVER (PARTITION BY CC_NUM)=0 THEN 0 ELSE DISTANCE_KM/(AVG(DISTANCE_KM) OVER (PARTITION BY CC_NUM)*3) END, 1.0) AS LS FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS WHERE LOCATION_SCORE IS NULL) ls WHERE t.ID = ls.ID;

    UPDATE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS t SET AMOUNT_SCORE = a.AMS
    FROM (SELECT ID, LEAST(CASE WHEN STDDEV(AMT) OVER (PARTITION BY CC_NUM)=0 OR STDDEV(AMT) OVER (PARTITION BY CC_NUM) IS NULL THEN CASE WHEN AMT>500 THEN 1.0 ELSE AMT/500.0 END ELSE ABS(AMT-AVG(AMT) OVER (PARTITION BY CC_NUM))/(STDDEV(AMT) OVER (PARTITION BY CC_NUM)*3) END, 1.0) AS AMS FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS WHERE AMOUNT_SCORE IS NULL) a WHERE t.ID = a.ID;

    UPDATE KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS SET RISK_SCORE = ROUND((COALESCE(AMOUNT_SCORE,0)*0.40)+(COALESCE(VELOCITY_SCORE,0)*0.35)+(COALESCE(LOCATION_SCORE,0)*0.25), 4) WHERE RISK_SCORE IS NULL;

    -- Log execution
    INSERT INTO KAGGLE_DB.BRONZE.PIPELINE_EXECUTION_LOG 
        (PROCEDURE_NAME, EXECUTION_STATUS, START_TIME, END_TIME, DURATION_SECONDS, ROWS_PROCESSED, BATCH_TIMESTAMP, WAREHOUSE_NAME)
    SELECT 'SP_BRONZE_TO_SILVER', 'SUCCESS', :v_start, CURRENT_TIMESTAMP(), DATEDIFF('SECOND', :v_start, CURRENT_TIMESTAMP()), COUNT(*), CURRENT_TIMESTAMP(), CURRENT_WAREHOUSE()
    FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS WHERE INGESTED_AT >= :v_start;

    RETURN 'SP_BRONZE_TO_SILVER completed successfully.';
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO KAGGLE_DB.BRONZE.PIPELINE_ERROR_LOG (PROCEDURE_NAME, ERROR_CODE, ERROR_MESSAGE, ERROR_STATE, STACK_TRACE)
        VALUES ('SP_BRONZE_TO_SILVER', :SQLCODE, :SQLERRM, :SQLSTATE, CURRENT_STATEMENT());
        INSERT INTO KAGGLE_DB.BRONZE.PIPELINE_EXECUTION_LOG (PROCEDURE_NAME, EXECUTION_STATUS, START_TIME, END_TIME, DURATION_SECONDS, BATCH_TIMESTAMP, WAREHOUSE_NAME)
        VALUES ('SP_BRONZE_TO_SILVER', 'FAILED', :v_start, CURRENT_TIMESTAMP(), DATEDIFF('SECOND', :v_start, CURRENT_TIMESTAMP()), CURRENT_TIMESTAMP(), CURRENT_WAREHOUSE());
        RAISE;
END;
$$;

-- Silver to Gold
CREATE OR REPLACE PROCEDURE KAGGLE_DB.GOLD.SP_SILVER_TO_GOLD()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    error_msg VARCHAR;
    v_start TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP();
BEGIN
    IF (NOT SYSTEM$STREAM_HAS_DATA('KAGGLE_DB.SILVER.STM_ENRICHED_TRANSACTIONS')) THEN
        INSERT INTO KAGGLE_DB.BRONZE.PIPELINE_EXECUTION_LOG 
            (PROCEDURE_NAME, EXECUTION_STATUS, START_TIME, END_TIME, DURATION_SECONDS, ROWS_PROCESSED, BATCH_TIMESTAMP, WAREHOUSE_NAME)
        VALUES ('SP_SILVER_TO_GOLD', 'SKIPPED', :v_start, CURRENT_TIMESTAMP(), 0, 0, CURRENT_TIMESTAMP(), CURRENT_WAREHOUSE());
        RETURN 'No new data in stream. Skipping.';
    END IF;

    MERGE INTO KAGGLE_DB.GOLD.DIM_CUSTOMER AS tgt
    USING (SELECT DISTINCT CC_NUM, FIRST, LAST, GENDER, DOB, JOB, DATEDIFF('YEAR', DOB, CURRENT_DATE()) AS AGE FROM KAGGLE_DB.SILVER.STM_ENRICHED_TRANSACTIONS WHERE METADATA$ACTION = 'INSERT') AS src
    ON tgt.CC_NUM = src.CC_NUM
    WHEN NOT MATCHED THEN INSERT (CUSTOMER_SK, CC_NUM, FIRST, LAST, GENDER, DOB, JOB, AGE)
    VALUES ((SELECT COALESCE(MAX(CUSTOMER_SK),0)+1 FROM KAGGLE_DB.GOLD.DIM_CUSTOMER), src.CC_NUM, src.FIRST, src.LAST, src.GENDER, src.DOB, src.JOB, src.AGE);

    MERGE INTO KAGGLE_DB.GOLD.DIM_MERCHANT AS tgt
    USING (SELECT DISTINCT MERCHANT, CATEGORY, ROUND(AVG(MERCH_LAT),4) AS AVG_MERCH_LAT, ROUND(AVG(MERCH_LONG),4) AS AVG_MERCH_LONG, COUNT(*) AS TRANSACTION_COUNT FROM KAGGLE_DB.SILVER.STM_ENRICHED_TRANSACTIONS WHERE METADATA$ACTION = 'INSERT' GROUP BY MERCHANT, CATEGORY) AS src
    ON tgt.MERCHANT = src.MERCHANT AND tgt.CATEGORY = src.CATEGORY
    WHEN NOT MATCHED THEN INSERT (MERCHANT_SK, MERCHANT, CATEGORY, AVG_MERCH_LAT, AVG_MERCH_LONG, TRANSACTION_COUNT)
    VALUES ((SELECT COALESCE(MAX(MERCHANT_SK),0)+1 FROM KAGGLE_DB.GOLD.DIM_MERCHANT), src.MERCHANT, src.CATEGORY, src.AVG_MERCH_LAT, src.AVG_MERCH_LONG, src.TRANSACTION_COUNT);

    MERGE INTO KAGGLE_DB.GOLD.DIM_LOCATION AS tgt
    USING (SELECT DISTINCT CITY, STATE, ZIP, LAT, LONG, CITY_POP FROM KAGGLE_DB.SILVER.STM_ENRICHED_TRANSACTIONS WHERE METADATA$ACTION = 'INSERT') AS src
    ON tgt.CITY = src.CITY AND tgt.STATE = src.STATE AND tgt.ZIP = src.ZIP
    WHEN NOT MATCHED THEN INSERT (LOCATION_SK, CITY, STATE, ZIP, LAT, LONG, CITY_POP)
    VALUES ((SELECT COALESCE(MAX(LOCATION_SK),0)+1 FROM KAGGLE_DB.GOLD.DIM_LOCATION), src.CITY, src.STATE, src.ZIP, src.LAT, src.LONG, src.CITY_POP);

    MERGE INTO KAGGLE_DB.GOLD.DIM_DATE AS tgt
    USING (SELECT DISTINCT DATE(TRANS_DATE_TRANS_TIME) AS DATE_KEY, YEAR(TRANS_DATE_TRANS_TIME) AS YEAR, MONTH(TRANS_DATE_TRANS_TIME) AS MONTH, MONTHNAME(TRANS_DATE_TRANS_TIME) AS MONTH_NAME, DAY(TRANS_DATE_TRANS_TIME) AS DAY_OF_MONTH, DAYNAME(TRANS_DATE_TRANS_TIME) AS DAY_NAME, DAYOFWEEK(TRANS_DATE_TRANS_TIME) AS DAY_OF_WEEK, QUARTER(TRANS_DATE_TRANS_TIME) AS QUARTER, WEEKOFYEAR(TRANS_DATE_TRANS_TIME) AS WEEK_OF_YEAR FROM KAGGLE_DB.SILVER.STM_ENRICHED_TRANSACTIONS WHERE METADATA$ACTION = 'INSERT') AS src
    ON tgt.DATE_KEY = src.DATE_KEY
    WHEN NOT MATCHED THEN INSERT (DATE_SK, DATE_KEY, YEAR, MONTH, MONTH_NAME, DAY_OF_MONTH, DAY_NAME, DAY_OF_WEEK, QUARTER, WEEK_OF_YEAR)
    VALUES ((SELECT COALESCE(MAX(DATE_SK),0)+1 FROM KAGGLE_DB.GOLD.DIM_DATE), src.DATE_KEY, src.YEAR, src.MONTH, src.MONTH_NAME, src.DAY_OF_MONTH, src.DAY_NAME, src.DAY_OF_WEEK, src.QUARTER, src.WEEK_OF_YEAR);

    INSERT INTO KAGGLE_DB.GOLD.FACT_TRANSACTIONS
    SELECT t.ID, t.TRANS_NUM, c.CUSTOMER_SK, m.MERCHANT_SK, l.LOCATION_SK, d.DATE_SK,
        ts.TIME_SLOT_SK, ab.AMOUNT_BUCKET_SK, ag.AGE_BUCKET_SK, rb.RISK_BAND_SK, tz.TIMEZONE_SK,
        t.TRANS_DATE_TRANS_TIME, t.LOCAL_TRANS_TIME, t.AMT, t.DISTANCE_KM, t.IS_FRAUD,
        t.VELOCITY_SCORE, t.LOCATION_SCORE, t.AMOUNT_SCORE, t.RISK_SCORE
    FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS t
    LEFT JOIN KAGGLE_DB.GOLD.DIM_CUSTOMER c ON t.CC_NUM = c.CC_NUM
    LEFT JOIN KAGGLE_DB.GOLD.DIM_MERCHANT m ON t.MERCHANT = m.MERCHANT AND t.CATEGORY = m.CATEGORY
    LEFT JOIN KAGGLE_DB.GOLD.DIM_LOCATION l ON t.CITY = l.CITY AND t.STATE = l.STATE AND t.ZIP = l.ZIP
    LEFT JOIN KAGGLE_DB.GOLD.DIM_DATE d ON DATE(t.TRANS_DATE_TRANS_TIME) = d.DATE_KEY
    LEFT JOIN KAGGLE_DB.GOLD.DIM_TIME_SLOT ts ON t.LOCAL_HOUR = ts.HOUR_OF_DAY
    LEFT JOIN KAGGLE_DB.GOLD.DIM_AMOUNT_BUCKET ab ON t.AMOUNT_BUCKET = ab.AMOUNT_BUCKET
    LEFT JOIN KAGGLE_DB.GOLD.DIM_AGE_BUCKET ag ON t.AGE >= ag.AGE_MIN AND t.AGE <= ag.AGE_MAX
    LEFT JOIN KAGGLE_DB.GOLD.DIM_RISK_BAND rb ON t.RISK_SCORE >= rb.RISK_MIN AND t.RISK_SCORE < rb.RISK_MAX
    LEFT JOIN KAGGLE_DB.GOLD.DIM_TIMEZONE tz ON t.TIMEZONE = tz.TIMEZONE_NAME
    WHERE t.ID NOT IN (SELECT TRANSACTION_ID FROM KAGGLE_DB.GOLD.FACT_TRANSACTIONS);

    INSERT INTO KAGGLE_DB.BRONZE.PIPELINE_EXECUTION_LOG 
        (PROCEDURE_NAME, EXECUTION_STATUS, START_TIME, END_TIME, DURATION_SECONDS, ROWS_PROCESSED, BATCH_TIMESTAMP, WAREHOUSE_NAME)
    SELECT 'SP_SILVER_TO_GOLD', 'SUCCESS', :v_start, CURRENT_TIMESTAMP(), DATEDIFF('SECOND', :v_start, CURRENT_TIMESTAMP()), COUNT(*), CURRENT_TIMESTAMP(), CURRENT_WAREHOUSE()
    FROM KAGGLE_DB.GOLD.FACT_TRANSACTIONS WHERE TRANS_DATE_TRANS_TIME >= :v_start;

    RETURN 'SP_SILVER_TO_GOLD completed successfully.';
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO KAGGLE_DB.BRONZE.PIPELINE_ERROR_LOG (PROCEDURE_NAME, ERROR_CODE, ERROR_MESSAGE, ERROR_STATE, STACK_TRACE)
        VALUES ('SP_SILVER_TO_GOLD', :SQLCODE, :SQLERRM, :SQLSTATE, CURRENT_STATEMENT());
        INSERT INTO KAGGLE_DB.BRONZE.PIPELINE_EXECUTION_LOG (PROCEDURE_NAME, EXECUTION_STATUS, START_TIME, END_TIME, DURATION_SECONDS, BATCH_TIMESTAMP, WAREHOUSE_NAME)
        VALUES ('SP_SILVER_TO_GOLD', 'FAILED', :v_start, CURRENT_TIMESTAMP(), DATEDIFF('SECOND', :v_start, CURRENT_TIMESTAMP()), CURRENT_TIMESTAMP(), CURRENT_WAREHOUSE());
        RAISE;
END;
$$;

-- Schema Checkpoint
CREATE OR REPLACE PROCEDURE KAGGLE_DB.BRONZE.SP_SCHEMA_CHECKPOINT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    new_cols_count NUMBER DEFAULT 0;
    result_msg VARCHAR DEFAULT '';
BEGIN
    INSERT INTO KAGGLE_DB.BRONZE.SCHEMA_REGISTRY (LAYER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHANGE_TYPE)
    SELECT 'BRONZE', 'RAW_TRANSACTIONS', b.COLUMN_NAME, b.DATA_TYPE, 'ADDED'
    FROM KAGGLE_DB.INFORMATION_SCHEMA.COLUMNS b
    WHERE b.TABLE_SCHEMA = 'BRONZE' AND b.TABLE_NAME = 'RAW_TRANSACTIONS'
        AND b.COLUMN_NAME NOT IN (SELECT COLUMN_NAME FROM KAGGLE_DB.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'SILVER' AND TABLE_NAME = 'ENRICHED_TRANSACTIONS')
        AND b.COLUMN_NAME NOT IN (SELECT COLUMN_NAME FROM KAGGLE_DB.BRONZE.SCHEMA_REGISTRY WHERE LAYER = 'BRONZE' AND CHANGE_TYPE = 'ADDED' AND IS_PROPAGATED = FALSE);

    SELECT COUNT(*) INTO new_cols_count FROM KAGGLE_DB.BRONZE.SCHEMA_REGISTRY WHERE LAYER = 'BRONZE' AND CHANGE_TYPE = 'ADDED' AND IS_PROPAGATED = FALSE;

    IF (new_cols_count > 0) THEN
        result_msg := 'WARNING: ' || new_cols_count || ' new column(s) detected in Bronze not yet in Silver.';
    ELSE
        result_msg := 'Schema checkpoint passed. Bronze and Silver are aligned.';
    END IF;
    RETURN result_msg;
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO KAGGLE_DB.BRONZE.PIPELINE_ERROR_LOG (PROCEDURE_NAME, ERROR_CODE, ERROR_MESSAGE, ERROR_STATE, STACK_TRACE)
        VALUES ('SP_SCHEMA_CHECKPOINT', :SQLCODE, :SQLERRM, :SQLSTATE, CURRENT_STATEMENT());
        RAISE;
END;
$$;

-- Rapid Fire Fraud Detection
CREATE OR REPLACE PROCEDURE KAGGLE_DB.FRAUD_ANALYSIS.SP_DETECT_RAPID_FIRE_FRAUD()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    error_msg VARCHAR;
BEGIN
    INSERT INTO KAGGLE_DB.FRAUD_ANALYSIS.FRAUD_ALERTS 
        (ALERT_TYPE, CC_NUM, MERCHANT, TRANSACTION_ID, AMT, RISK_SCORE, MERCHANT_SCORE, ALERT_REASON, ALERT_SEVERITY)
    SELECT 'RAPID_FIRE', t.CC_NUM, t.MERCHANT, t.ID, t.AMT, t.RISK_SCORE, t.MERCHANT_SCORE,
        'Multiple transactions within 5 minutes. Count in window: ' || txn_count || '. Total amount: $' || ROUND(window_total, 2),
        CASE WHEN txn_count >= 5 THEN 'CRITICAL' WHEN txn_count >= 3 THEN 'HIGH' ELSE 'MEDIUM' END
    FROM (
        SELECT ID, CC_NUM, MERCHANT, AMT, RISK_SCORE, MERCHANT_SCORE,
            COUNT(*) OVER (PARTITION BY CC_NUM ORDER BY TRANS_DATE_TRANS_TIME RANGE BETWEEN INTERVAL '5 MINUTES' PRECEDING AND CURRENT ROW) AS txn_count,
            SUM(AMT) OVER (PARTITION BY CC_NUM ORDER BY TRANS_DATE_TRANS_TIME RANGE BETWEEN INTERVAL '5 MINUTES' PRECEDING AND CURRENT ROW) AS window_total
        FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
        WHERE TRANS_DATE_TRANS_TIME >= DATEADD('MINUTE', -10, CURRENT_TIMESTAMP())
    ) t
    WHERE t.txn_count >= 2
    AND t.ID NOT IN (SELECT TRANSACTION_ID FROM KAGGLE_DB.FRAUD_ANALYSIS.FRAUD_ALERTS WHERE ALERT_TYPE = 'RAPID_FIRE');

    RETURN 'Rapid-fire detection complete.';
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO KAGGLE_DB.BRONZE.PIPELINE_ERROR_LOG (PROCEDURE_NAME, ERROR_CODE, ERROR_MESSAGE, ERROR_STATE, STACK_TRACE)
        VALUES ('SP_DETECT_RAPID_FIRE_FRAUD', :SQLCODE, :SQLERRM, :SQLSTATE, CURRENT_STATEMENT());
        RAISE;
END;
$$;
