-- ============================================
-- 09: DEEP-DIVE ANALYSIS (Phase 2)
-- ============================================

-- ============================================
-- A. FRAUD CHAINS — Same card, multiple frauds in sequence
-- How long do fraudsters exploit a card before it's caught?
-- ============================================

SELECT 
    CC_NUM,
    COUNT(*) AS FRAUD_CHAIN_LENGTH,
    MIN(TRANS_DATE_TRANS_TIME) AS FIRST_FRAUD,
    MAX(TRANS_DATE_TRANS_TIME) AS LAST_FRAUD,
    DATEDIFF('HOUR', MIN(TRANS_DATE_TRANS_TIME), MAX(TRANS_DATE_TRANS_TIME)) AS CHAIN_DURATION_HOURS,
    ROUND(SUM(AMT), 2) AS TOTAL_FRAUD_AMOUNT,
    ROUND(AVG(AMT), 2) AS AVG_PER_FRAUD
FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
WHERE IS_FRAUD = 1
GROUP BY CC_NUM
HAVING COUNT(*) >= 3
ORDER BY CHAIN_DURATION_HOURS DESC;

-- ============================================
-- B. FIRST FRAUD TIMING — How long after first legit txn does fraud start?
-- Card compromise timeline
-- ============================================

SELECT 
    CASE 
        WHEN DAYS_TO_FIRST_FRAUD < 1 THEN 'Same day'
        WHEN DAYS_TO_FIRST_FRAUD < 7 THEN '1-7 days'
        WHEN DAYS_TO_FIRST_FRAUD < 30 THEN '1-4 weeks'
        WHEN DAYS_TO_FIRST_FRAUD < 90 THEN '1-3 months'
        ELSE '3+ months'
    END AS TIME_TO_COMPROMISE,
    COUNT(*) AS CUSTOMERS,
    ROUND(AVG(TOTAL_FRAUD_LOSS), 2) AS AVG_LOSS_PER_CUSTOMER
FROM (
    SELECT 
        CC_NUM,
        DATEDIFF('DAY', 
            MIN(CASE WHEN IS_FRAUD = 0 THEN TRANS_DATE_TRANS_TIME END),
            MIN(CASE WHEN IS_FRAUD = 1 THEN TRANS_DATE_TRANS_TIME END)
        ) AS DAYS_TO_FIRST_FRAUD,
        SUM(CASE WHEN IS_FRAUD = 1 THEN AMT ELSE 0 END) AS TOTAL_FRAUD_LOSS
    FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
    GROUP BY CC_NUM
    HAVING SUM(IS_FRAUD) > 0
)
WHERE DAYS_TO_FIRST_FRAUD IS NOT NULL
GROUP BY TIME_TO_COMPROMISE
ORDER BY MIN(DAYS_TO_FIRST_FRAUD);

-- ============================================
-- C. MERCHANT-TO-MERCHANT PATTERNS — Which merchants are hit together?
-- Fraud rings / shared breaches
-- ============================================

SELECT 
    a.MERCHANT AS MERCHANT_1,
    b.MERCHANT AS MERCHANT_2,
    COUNT(DISTINCT a.CC_NUM) AS SHARED_FRAUD_CUSTOMERS,
    ROUND(AVG(a.AMT + b.AMT), 2) AS AVG_COMBINED_LOSS
FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS a
JOIN KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS b
    ON a.CC_NUM = b.CC_NUM
    AND a.IS_FRAUD = 1 AND b.IS_FRAUD = 1
    AND a.MERCHANT < b.MERCHANT
    AND ABS(DATEDIFF('HOUR', a.TRANS_DATE_TRANS_TIME, b.TRANS_DATE_TRANS_TIME)) <= 24
GROUP BY a.MERCHANT, b.MERCHANT
HAVING SHARED_FRAUD_CUSTOMERS >= 3
ORDER BY SHARED_FRAUD_CUSTOMERS DESC
LIMIT 20;

-- ============================================
-- D. CITY-LEVEL CLUSTERING — Fraud density per capita
-- True hotspots (not just volume)
-- ============================================

SELECT 
    CITY,
    STATE,
    CITY_POP,
    COUNT(*) AS TOTAL_TXNS,
    SUM(IS_FRAUD) AS FRAUD_COUNT,
    ROUND(SUM(IS_FRAUD)*100.0/COUNT(*), 2) AS FRAUD_RATE_PCT,
    ROUND(SUM(IS_FRAUD)*100000.0/CITY_POP, 2) AS FRAUD_PER_100K_POP,
    ROUND(SUM(CASE WHEN IS_FRAUD=1 THEN AMT ELSE 0 END), 2) AS FRAUD_LOSS
FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
GROUP BY CITY, STATE, CITY_POP
HAVING FRAUD_COUNT >= 3
ORDER BY FRAUD_PER_100K_POP DESC
LIMIT 20;

-- ============================================
-- E. WEEKEND VS WEEKDAY — By category + time
-- Behavioral shifts
-- ============================================

SELECT 
    CASE WHEN DAYOFWEEK(TRANS_DATE_TRANS_TIME) IN (0, 6) THEN 'WEEKEND' ELSE 'WEEKDAY' END AS DAY_TYPE,
    CATEGORY,
    TIME_OF_DAY,
    COUNT(*) AS TOTAL_TXNS,
    SUM(IS_FRAUD) AS FRAUD_COUNT,
    ROUND(SUM(IS_FRAUD)*100.0/COUNT(*), 2) AS FRAUD_RATE_PCT
FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
GROUP BY DAY_TYPE, CATEGORY, TIME_OF_DAY
HAVING FRAUD_COUNT > 0
ORDER BY FRAUD_RATE_PCT DESC
LIMIT 30;

-- ============================================
-- F. AMOUNT DISTRIBUTION — Legit vs Fraud comparison
-- Where the cutoff really is
-- ============================================

SELECT 
    CASE 
        WHEN AMT < 5 THEN '0-5'
        WHEN AMT < 10 THEN '5-10'
        WHEN AMT < 25 THEN '10-25'
        WHEN AMT < 50 THEN '25-50'
        WHEN AMT < 100 THEN '50-100'
        WHEN AMT < 200 THEN '100-200'
        WHEN AMT < 300 THEN '200-300'
        WHEN AMT < 400 THEN '300-400'
        WHEN AMT < 500 THEN '400-500'
        WHEN AMT < 750 THEN '500-750'
        WHEN AMT < 1000 THEN '750-1000'
        ELSE '1000+'
    END AS AMOUNT_RANGE,
    COUNT(CASE WHEN IS_FRAUD = 0 THEN 1 END) AS LEGIT_COUNT,
    COUNT(CASE WHEN IS_FRAUD = 1 THEN 1 END) AS FRAUD_COUNT,
    ROUND(COUNT(CASE WHEN IS_FRAUD = 1 THEN 1 END)*100.0/NULLIF(COUNT(*), 0), 2) AS FRAUD_RATE_PCT
FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
GROUP BY AMOUNT_RANGE
ORDER BY MIN(AMT);

-- ============================================
-- G. CUSTOMER LIFETIME VALUE VS FRAUD LOSS
-- Who to protect first (high value customers losing most)
-- ============================================

SELECT 
    CASE 
        WHEN TOTAL_SPEND >= 50000 THEN 'VIP (50K+)'
        WHEN TOTAL_SPEND >= 20000 THEN 'HIGH (20-50K)'
        WHEN TOTAL_SPEND >= 10000 THEN 'MEDIUM (10-20K)'
        WHEN TOTAL_SPEND >= 5000 THEN 'LOW (5-10K)'
        ELSE 'MICRO (<5K)'
    END AS CUSTOMER_TIER,
    COUNT(*) AS CUSTOMERS,
    SUM(FRAUD_COUNT) AS TOTAL_FRAUDS,
    ROUND(AVG(FRAUD_LOSS), 2) AS AVG_FRAUD_LOSS,
    ROUND(SUM(FRAUD_LOSS), 2) AS TOTAL_FRAUD_LOSS,
    ROUND(SUM(FRAUD_LOSS)*100.0/SUM(TOTAL_SPEND), 2) AS FRAUD_LOSS_PCT_OF_SPEND
FROM (
    SELECT 
        CC_NUM,
        SUM(AMT) AS TOTAL_SPEND,
        SUM(IS_FRAUD) AS FRAUD_COUNT,
        SUM(CASE WHEN IS_FRAUD = 1 THEN AMT ELSE 0 END) AS FRAUD_LOSS
    FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
    GROUP BY CC_NUM
)
GROUP BY CUSTOMER_TIER
ORDER BY MIN(TOTAL_SPEND) DESC;

-- ============================================
-- H. REPEAT MERCHANT FRAUD — Same merchant, different victims
-- Compromised merchant detection
-- ============================================

SELECT 
    MERCHANT,
    CATEGORY,
    COUNT(DISTINCT CC_NUM) AS UNIQUE_VICTIMS,
    SUM(IS_FRAUD) AS TOTAL_FRAUDS,
    ROUND(SUM(CASE WHEN IS_FRAUD=1 THEN AMT ELSE 0 END), 2) AS TOTAL_FRAUD_LOSS,
    MIN(TRANS_DATE_TRANS_TIME) AS FIRST_FRAUD_DATE,
    MAX(TRANS_DATE_TRANS_TIME) AS LAST_FRAUD_DATE,
    DATEDIFF('DAY', MIN(TRANS_DATE_TRANS_TIME), MAX(TRANS_DATE_TRANS_TIME)) AS FRAUD_SPAN_DAYS
FROM KAGGLE_DB.SILVER.ENRICHED_TRANSACTIONS
WHERE IS_FRAUD = 1
GROUP BY MERCHANT, CATEGORY
HAVING UNIQUE_VICTIMS >= 5
ORDER BY UNIQUE_VICTIMS DESC
LIMIT 20;
